version: '3.9'


networks:
  default:
    name: 'english_hub'

volumes:
  postgres:
  logs:

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '1111'
      POSTGRES_USER: 'shombal'
      POSTGRES_DB: 'english_hub'
  
  opensearch:
    image: 'opensearchproject/opensearch:latest'
    container_name: 'opensearch'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'OJxZer7nM1'
    volumes:
      - logs:/usr/share/opensearch/data
  
  opensearch-dashboards:
    image: 'opensearchproject/opensearch-dashboards:latest'
    container_name: 'opensearch_dashboards'
    ports:
      - '5601:5601'
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'