version: '3.9'


networks:
  default:
    name: 'english_hub'

volumes:
  postgres:
  logs:
  prometheus:
  grafana:

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '1111'
      POSTGRES_USER: 'shombal'
      POSTGRES_DB: 'english_hub'
  
  opensearch:
    image: 'opensearchproject/opensearch:latest'
    container_name: 'opensearch'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'OJxZer7nM1'
    volumes:
      - logs:/usr/share/opensearch/data
  
  opensearch-dashboards:
    image: 'opensearchproject/opensearch-dashboards:latest'
    container_name: 'opensearch_dashboards'
    ports:
      - '5601:5601'
    expose:
      - "5601" 
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
      
  prometheus:
    image: 'prom/prometheus'
    container_name: 'english-hub-prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  
  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    depends_on: 
      - prometheus
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel, grafana-simple-json-datasource'
  
  jaeger:
    image: 'jaegertracing/all-in-one'
    container_name: 'jaeger'
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - '6831:6831/udp' 
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686' 
      - '4317:4317' 
      - '4318:4318'
      - '14250:14250' 
      - '14268:14268' 
      - '14269:14269' 
      - '9411:9411' 